# -*- coding: utf-8 -*-
"""Json Refiner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSU9Z73uhaAtCrtGCOcwjse2YuXuxOaV
"""

!pip install gradio pandas

import json
import pandas as pd
import gradio as gr

# Function to remove null values
def remove_nulls(data):
    if isinstance(data, dict):
        return {k: remove_nulls(v) for k, v in data.items() if v is not None}
    elif isinstance(data, list):
        return [remove_nulls(v) for v in data if v is not None]
    else:
        return data

# Flatten JSON
def flatten_json(y, prefix=''):
    out = {}
    if isinstance(y, dict):
        for k, v in y.items():
            out.update(flatten_json(v, f"{prefix}{k}_"))
    elif isinstance(y, list):
        for i, v in enumerate(y):
            out.update(flatten_json(v, f"{prefix}{i}_"))
    else:
        out[prefix[:-1]] = y
    return out

# Main refinery function
def refine_json(input_json):
    try:
        data = json.loads(input_json)

        # Remove null values
        cleaned = remove_nulls(data)

        # Pretty format
        formatted = json.dumps(cleaned, indent=4, sort_keys=True)

        # Flatten
        flat = flatten_json(cleaned)
        flat_json = json.dumps(flat, indent=4)

        # Convert to CSV
        df = pd.json_normalize(cleaned)
        csv_output = df.to_csv(index=False)

        return formatted, flat_json, csv_output

    except Exception as e:
        return f"Error: {str(e)}", "", ""

# Gradio UI
interface = gr.Interface(
    fn=refine_json,
    inputs=gr.Textbox(lines=15, placeholder="Paste your JSON here..."),
    outputs=[
        gr.Textbox(label="Formatted JSON"),
        gr.Textbox(label="Flattened JSON"),
        gr.Textbox(label="CSV Output")
    ],
    title="JSON Refinery Tool",
    description="Clean, format, flatten and convert JSON to CSV"
)

interface.launch()